# Gitleaks Configuration for living-docs
# Prevents secrets and credentials from being committed

title = "living-docs gitleaks config"

[allowlist]
description = "Allowlisted patterns and files"

# Paths to ignore
paths = [
    "specs/SEC-002-secrets-scan.md",
    "tests/**",
    "test/**",
    ".*_test.*",
    ".gitleaks.toml",
    "docs/procedures/pr-protocol.md"
]

# Regexes to allow (example patterns in documentation)
regexes = [
    '''example\.com''',
    '''test@example\.com''',
    '''sk-[0-9a-zA-Z]{32,45}''' # Example API key patterns in docs
]

# Custom rules for living-docs specific patterns
[[rules]]
id = "living-docs-api-key"
description = "Living Docs API Key Detection"
regex = '''(?i)(living[_-]?docs[_-]?api[_-]?key)(.{0,20})?['\"]([0-9a-zA-Z]{32,45})['\"]'''
tags = ["api-key", "living-docs"]

[[rules]]
id = "adapter-secret"
description = "Adapter Configuration Secret"
regex = '''(?i)(adapter[_-]?secret|adapter[_-]?token)(.{0,20})?['\"]([0-9a-zA-Z]{20,})['\"]'''
tags = ["secret", "adapter"]

[[rules]]
id = "manifest-signing-key"
description = "Manifest Signing Key Detection"
regex = '''(?i)(manifest[_-]?key|signing[_-]?key)(.{0,20})?['\"]([0-9a-zA-Z]{16,})['\"]'''
tags = ["signing", "manifest"]

# Standard secret detection rules
[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)api[_-]?key['\s]*[:=]['\s]*['\"]([0-9a-zA-Z\-_]{20,})['\"]'''
tags = ["api-key", "generic"]

[[rules]]
id = "github-token"
description = "GitHub Personal Access Token"
regex = '''ghp_[0-9a-zA-Z]{36}'''
tags = ["github", "token"]

[[rules]]
id = "private-key"
description = "Private Key"
regex = '''(?i)-----BEGIN (RSA |EC |OPENSSH |DSA |ED25519 )?PRIVATE KEY-----'''
tags = ["private-key", "security"]

[[rules]]
id = "aws-access-key"
description = "AWS Access Key"
regex = '''(?i)aws[_-]?access[_-]?key[_-]?id['\s]*[:=]['\s]*['\"]?(AKIA[0-9A-Z]{16})['\"]?'''
tags = ["aws", "credentials"]

[[rules]]
id = "aws-secret-key"
description = "AWS Secret Key"
regex = '''(?i)aws[_-]?secret[_-]?access[_-]?key['\s]*[:=]['\s]*['\"]?([0-9a-zA-Z+/]{40})['\"]?'''
tags = ["aws", "credentials"]

[[rules]]
id = "password-in-config"
description = "Password in Configuration"
regex = '''(?i)(password|passwd|pwd)['\s]*[:=]['\s]*['\"](.{8,})['\"]'''
tags = ["password", "credentials"]
[rules.allowlist]
regexes = [
    '''password['\s]*[:=]['\s]*['\"](\*+|<.*?>|example|test|demo|dummy)['\"]'''
]

[[rules]]
id = "slack-token"
description = "Slack Token"
regex = '''xox[baprs]-([0-9a-zA-Z]{10,48})'''
tags = ["slack", "token"]

[[rules]]
id = "database-url"
description = "Database Connection String"
regex = '''(?i)(postgres|postgresql|mysql|mongodb|redis)://[^:]+:[^@]+@[^/]+/[^\s]+'''
tags = ["database", "credentials"]
[rules.allowlist]
regexes = [
    '''(postgres|mysql)://user:password@localhost'''
]

# Version tracking
[extend]
useDefault = true