name: spec-kit
version: 2.0.0  # Adapter wrapper version
upstream_version: v0.0.47  # GitHub spec-kit release version
description: GitHub's specification-driven development toolkit
author: GitHub
license: MIT
homepage: https://github.com/github/spec-kit

# Spec-kit uses multiple directories
files:
  - source: templates/memory/
    dest: "{{MEMORY_PATH}}/"
  - source: templates/specs/
    dest: "{{SPECS_PATH}}/"
  - source: templates/scripts/
    dest: "{{SCRIPTS_PATH}}/"
  - source: templates/.github/
    dest: ".github/"
  - source: templates/commands/
    dest: "{{MEMORY_PATH}}/commands/"
  - source: templates/agent-file-template.md
    dest: "{{MEMORY_PATH}}/agent-file-template.md"
  - source: templates/plan-template.md
    dest: "{{SPECS_PATH}}/plan-template.md"
  - source: templates/spec-template.md
    dest: "{{SPECS_PATH}}/spec-template.md"
  - source: templates/tasks-template.md
    dest: "{{SPECS_PATH}}/tasks-template.md"

# No hard dependencies
dependencies: []

# Claims these directories
claims:
  - "{{MEMORY_PATH}}"
  - "{{SPECS_PATH}}"
  - "{{SCRIPTS_PATH}}"

# No conflicts with other adapters
conflicts: []

# Works with all AI assistants
ai_assistants:
  - claude
  - copilot
  - cursor
  - aider
  - continue

# Requires path rewriting for custom locations
requires_path_rewrite: true