#!/bin/bash
# a11y/config.sh - Accessibility configuration module
# Extracted from check.sh as part of DEBT-001 refactoring

set -euo pipefail

# Default configuration
readonly A11Y_DEFAULT_REPORT_DIR="reports/accessibility"
readonly A11Y_DEFAULT_FORMAT="text"
readonly A11Y_DEFAULT_SEVERITY="warning"
readonly A11Y_DEFAULT_MAX_ISSUES=100

# WCAG levels
readonly WCAG_LEVEL_A="A"
readonly WCAG_LEVEL_AA="AA"
readonly WCAG_LEVEL_AAA="AAA"

# Issue severities
readonly SEVERITY_CRITICAL="critical"
readonly SEVERITY_WARNING="warning"
readonly SEVERITY_INFO="info"

# Configuration variables
A11Y_REPORT_DIR="${A11Y_REPORT_DIR:-$A11Y_DEFAULT_REPORT_DIR}"
A11Y_FORMAT="${A11Y_FORMAT:-$A11Y_DEFAULT_FORMAT}"
A11Y_SEVERITY="${A11Y_SEVERITY:-$A11Y_DEFAULT_SEVERITY}"
A11Y_MAX_ISSUES="${A11Y_MAX_ISSUES:-$A11Y_DEFAULT_MAX_ISSUES}"
A11Y_WCAG_LEVEL="${A11Y_WCAG_LEVEL:-$WCAG_LEVEL_AA}"

# Load configuration from file
load_a11y_config() {
    local config_file="${1:-${PROJECT_ROOT:-$(pwd)}/.living-docs/a11y.config}"

    if [[ ! -f "$config_file" ]]; then
        return 0  # Use defaults
    fi

    # Source config file
    # shellcheck source=/dev/null
    source "$config_file"

    return 0
}

# Save configuration to file
save_a11y_config() {
    local config_file="${1:-${PROJECT_ROOT:-$(pwd)}/.living-docs/a11y.config}"

    mkdir -p "$(dirname "$config_file")"

    cat > "$config_file" << EOF
# Accessibility Configuration
# Generated by living-docs

# Report directory
A11Y_REPORT_DIR="$A11Y_REPORT_DIR"

# Output format (text, json, html, csv)
A11Y_FORMAT="$A11Y_FORMAT"

# Minimum severity to report (critical, warning, info)
A11Y_SEVERITY="$A11Y_SEVERITY"

# Maximum issues to report
A11Y_MAX_ISSUES=$A11Y_MAX_ISSUES

# WCAG compliance level (A, AA, AAA)
A11Y_WCAG_LEVEL="$A11Y_WCAG_LEVEL"
EOF

    return 0
}

# Get configuration value
get_a11y_config() {
    local key="${1:-}"

    case "$key" in
        report_dir)
            echo "$A11Y_REPORT_DIR"
            ;;
        format)
            echo "$A11Y_FORMAT"
            ;;
        severity)
            echo "$A11Y_SEVERITY"
            ;;
        max_issues)
            echo "$A11Y_MAX_ISSUES"
            ;;
        wcag_level)
            echo "$A11Y_WCAG_LEVEL"
            ;;
        *)
            return 1
            ;;
    esac
}

# Set configuration value
set_a11y_config() {
    local key="${1:-}"
    local value="${2:-}"

    case "$key" in
        report_dir)
            A11Y_REPORT_DIR="$value"
            ;;
        format)
            A11Y_FORMAT="$value"
            ;;
        severity)
            A11Y_SEVERITY="$value"
            ;;
        max_issues)
            A11Y_MAX_ISSUES="$value"
            ;;
        wcag_level)
            A11Y_WCAG_LEVEL="$value"
            ;;
        *)
            return 1
            ;;
    esac
}

# Export configuration
export A11Y_REPORT_DIR
export A11Y_FORMAT
export A11Y_SEVERITY
export A11Y_MAX_ISSUES
export A11Y_WCAG_LEVEL

# Export functions
export -f load_a11y_config
export -f save_a11y_config
export -f get_a11y_config
export -f set_a11y_config